//WANING: this code is autogenerated with GCA by FelipedelosH
package api.crazy.demo.infraestructure.entryPoints;

import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RestController;

//Dependencias para "Inyectar caso de uso"
import api.crazy.demo.domain.usecases.getAllTestOneVarIntUseCase.GetAllTestOneVarIntUseCase;
import api.crazy.demo.domain.usecases.getAllTestOneVarIntUseCase.GetAllTestOneVarIntUseCaseParam;


@RestController
public class getTestOneVarIntApiRest {

    private final GetAllTestOneVarIntUseCase getalltestonevarintusecase;

    public getTestOneVarIntApiRest(GetAllTestOneVarIntUseCase getalltestonevarintusecase){
        this.getalltestonevarintusecase = getalltestonevarintusecase;
    }

    @GetMapping("/getAllTestOneVarInt")
	public String index() {

        var response = getalltestonevarintusecase.call(GetAllTestOneVarIntUseCaseParam.build());

		return response.toString();
	}

}
