//WANING: this code is autogenerated with GCA by FelipedelosH
package api.crazy.demo.domain.entities;

public class TestOneVarInt {
    
	public int numero;


	public TestOneVarInt(){
	}

	public TestOneVarInt(int numero){
		this.numero = numero;
	}

	public void setNumero(int numero){
		this.numero = numero;
	}

	public int getNumero(){
		return this.numero;
	}




    @Override
    public String toString() {
        return 	"{" +
			"\"numero\":"  + numero +
		"}";
    }
    

}
