//WANING: this code is autogenerated with GCA by FelipedelosH
package api.crazy.demo.infraestructure.mappers;

import api.crazy.demo.domain.entities.TestOneVarInt;
import api.crazy.demo.infraestructure.DAO.TestOneVarIntDAO.TestOneVarIntEntity;

public class TestOneVarIntMapper {


    public static TestOneVarIntEntity toEntity(TestOneVarInt testonevarint) {
        return new TestOneVarIntEntity(testonevarint.getNumero());
    }
    


    public static TestOneVarInt toDomain(TestOneVarIntEntity testonevarint) {
        return new TestOneVarInt(testonevarint.getNumero());
    }
    

}
