//WANING: this code is autogenerated with GCA by FelipedelosH
package api.crazy.demo.infraestructure.mappers;

import api.crazy.demo.domain.entities.Product;
import api.crazy.demo.infraestructure.DAO.ProductDAO.ProductEntity;

public class ProductMapper {


    public static ProductEntity toEntity(Product product) {
        return new ProductEntity(product.getId(),product.getName(),product.getPrice());
    }
    


    public static Product toDomain(ProductEntity product) {
        return new Product(product.getId(),product.getName(),product.getPrice());
    }
    

}
