//WANING: this code is autogenerated with GCA by FelipedelosH
package api.crazy.demo.domain.usecases.getAllProductUseCase;

public class GetAllProductUseCaseParam {

    private GetAllProductUseCaseParam(){
    }

    //This is static becos not need instance... with put static you utilized without instance.
    //Only used a method
    public static GetAllProductUseCaseParam build(){
        return new GetAllProductUseCaseParam();
    }
    
}
