//WANING: this code is autogenerated with GCA by FelipedelosH
package api.crazy.demo.infraestructure.entryPoints;
import api.crazy.demo.domain.entities.StandarJsonResponse;

import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RestController;

//Dependencias para "Inyectar caso de uso"
import api.crazy.demo.domain.usecases.getAllExampleUseCase.GetAllExampleUseCase;
import api.crazy.demo.domain.usecases.getAllExampleUseCase.GetAllExampleUseCaseParam;


@RestController
public class getExampleApiRest {

    private final GetAllExampleUseCase getallexampleusecase;

    public getExampleApiRest(GetAllExampleUseCase getallexampleusecase){
        this.getallexampleusecase = getallexampleusecase;
    }

    @GetMapping("/getAllExample")
	public String index() {

        StandarJsonResponse resp = new StandarJsonResponse();

        try{
            var response = getallexampleusecase.call(GetAllExampleUseCaseParam.build());
            resp.setStatus(true);
            resp.setData(response.toString());
            resp.setCode("200");
        }catch (Exception e){
            resp.setStatus(false);
            resp.setData("[]");
            resp.setCode("500");
        }

        return resp.toString();
	}

}
