//WANING: this code is autogenerated with GCA by FelipedelosH
package api.crazy.demo.infraestructure.entryPoints;
import api.crazy.demo.domain.entities.StandarJsonResponse;

import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.bind.annotation.PathVariable;

//Dependencias para "Inyectar caso de uso"
import api.crazy.demo.domain.usecases.getExampleByIdUseCase.GetExampleByIdUseCase;
import api.crazy.demo.domain.usecases.getExampleByIdUseCase.GetExampleByIdUseCaseParam;


@RestController
public class getExampleByIdUrlApiRest {

    private final GetExampleByIdUseCase getExampleByIdUseCase;

    public getExampleByIdUrlApiRest(GetExampleByIdUseCase getExampleByIdUseCase){
        this.getExampleByIdUseCase = getExampleByIdUseCase;
    }

    @GetMapping("/getExampleById/{id}")
	public String index(@PathVariable("id") String id) {

        StandarJsonResponse resp = new StandarJsonResponse();

        try{
            var response = getExampleByIdUseCase.call(GetExampleByIdUseCaseParam.build(id));
            resp.setStatus(true);
            resp.setData(response.toString());
            resp.setCode("200");
        }catch (Exception e){
            resp.setStatus(false);
            resp.setData("[]");
            resp.setCode("500");
        }

        return resp.toString();
	}

}
