//WANING: this code is autogenerated with GCA by FelipedelosH
package api.crazy.demo.domain.usecases.getAllOrderUseCase;

public class GetAllOrderUseCaseParam {

    private GetAllOrderUseCaseParam(){
    }

    //This is static becos not need instance... with put static you utilized without instance.
    //Only used a method
    public static GetAllOrderUseCaseParam build(){
        return new GetAllOrderUseCaseParam();
    }
    
}
