//WANING: this code is autogenerated with GCA by FelipedelosH
package api.crazy.demo.domain.usecases.getAllUserUseCase;

public class GetAllUserUseCaseParam {

    private GetAllUserUseCaseParam(){
    }

    //This is static becos not need instance... with put static you utilized without instance.
    //Only used a method
    public static GetAllUserUseCaseParam build(){
        return new GetAllUserUseCaseParam();
    }
    
}
