//WANING: this code is autogenerated with GCA by FelipedelosH
package api.crazy.demo.infraestructure.DAO.TestOneVarIntDAO;

import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;

public interface TestOneVarIntRepository extends JpaRepository<TestOneVarIntEntity, > {

    @Query(
            value = "select * from <TABLE-DB-ENTITY>",
            nativeQuery = true
    )
    List<TestOneVarIntEntity> getAll();
    
}
