//WANING: this code is autogenerated with GCA by FelipedelosH
package api.crazy.demo.infraestructure.DAO.TestOneVarIntDAO;

import java.util.List;
import org.springframework.stereotype.Service;

import lombok.AllArgsConstructor;

@Service
@AllArgsConstructor
public class TestOneVarIntService {

    private final TestOneVarIntRepository testonevarintrepository;

    public List<TestOneVarIntEntity> getAll(){
        var x = testonevarintrepository.findAll();
        return x;
    }
    
}
