//WANING: this code is autogenerated with GCA by FelipedelosH
package api.crazy.demo.infraestructure.DAO.TestTwoVarIntDAO;

import java.util.List;
import org.springframework.stereotype.Service;

import lombok.AllArgsConstructor;

@Service
@AllArgsConstructor
public class TestTwoVarIntService {

    private final TestTwoVarIntRepository testtwovarintrepository;

    public List<TestTwoVarIntEntity> getAll(){
        var x = testtwovarintrepository.findAll();
        return x;
    }
    
}
