//WANING: this code is autogenerated with GCA by FelipedelosH
package api.crazy.demo.infraestructure.DAO.TestTwoVarIntDAO;

import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;

public interface TestTwoVarIntRepository extends JpaRepository<TestTwoVarIntEntity, String> {

    @Query(
            value = "select * from <TABLE-DB-ENTITY>",
            nativeQuery = true
    )
    List<TestTwoVarIntEntity> getAll();
    
}
