//WANING: this code is autogenerated with GCA by FelipedelosH
package api.crazy.demo.infraestructure.DAO.ExampleDAO;

import java.util.List;
import org.springframework.stereotype.Service;

import lombok.AllArgsConstructor;

@Service
@AllArgsConstructor
public class ExampleService {

    private final ExampleRepository examplerepository;

    public List<ExampleEntity> getAll(){
        var x = examplerepository.findAll();
        return x;
    }

    public ExampleEntity findById(String id){
        //Find by id it´s proporcionated by JPA not need creates in repository
        var x = examplerepository.findById(id).orElse(null);
        return x;
    }

    public void deleteById(String id) {
        examplerepository.deleteById(id);
    }
    
}
