//WANING: this code is autogenerated with GCA by FelipedelosH
package api.crazy.demo.infraestructure.mappers;

import api.crazy.demo.domain.entities.User;
import api.crazy.demo.infraestructure.DAO.UserDAO.UserEntity;

public class UserMapper {


    public static UserEntity toEntity(User user) {
        return new UserEntity(user.getId(),user.getUsername(),user.getContrasena(),user.getName(),user.getAge());
    }
    


    public static User toDomain(UserEntity user) {
        return new User(user.getId(),user.getUsername(),user.getContrasena(),user.getName(),user.getAge());
    }
    

}
