//WANING: this code is autogenerated with GCA by FelipedelosH
package api.crazy.demo.domain.usecases.getAllTestOneVarIntUseCase;

public class GetAllTestOneVarIntParam {

    private GetAllTestOneVarIntParam(){
    }

    //This is static becos not need instance... with put static you utilized without instance.
    //Only used a method
    public static GetAllTestOneVarIntParam build(){
        return new GetAllTestOneVarIntParam();
    }
    
}
