//WANING: this code is autogenerated with GCA by FelipedelosH
package api.crazy.demo.domain.usecases.getAllTestOneVarIntUseCase;

import java.util.List;
import api.crazy.demo.domain.entities.TestOneVarInt;

public abstract class GetAllTestOneVarIntUseCase {
    
    public abstract List<TestOneVarInt> call(GetAllTestOneVarIntParam param);

}