//WANING: this code is autogenerated with GCA by FelipedelosH
package api.crazy.demo.domain.usecases.getAllTestOneVarIntUseCase;

public class GetAllTestOneVarIntUseCaseParam {

    private GetAllTestOneVarIntUseCaseParam(){
    }

    //This is static becos not need instance... with put static you utilized without instance.
    //Only used a method
    public static GetAllTestOneVarIntUseCaseParam build(){
        return new GetAllTestOneVarIntUseCaseParam();
    }
    
}
