//WANING: this code is autogenerated with GCA by FelipedelosH
package api.crazy.demo.domain.usecases.getAllTestTwoVarIntUseCase;

import java.util.List;
import api.crazy.demo.domain.entities.TestTwoVarInt;

public abstract class GetAllTestTwoVarIntUseCase {
    
    public abstract List<TestTwoVarInt> call(GetAllTestTwoVarIntUseCaseParam param);

}