//WANING: this code is autogenerated with GCA by FelipedelosH
package api.crazy.demo.domain.usecases.getAllTestTwoVarIntUseCase;

public class GetAllTestTwoVarIntUseCaseParam {

    private GetAllTestTwoVarIntUseCaseParam(){
    }

    //This is static becos not need instance... with put static you utilized without instance.
    //Only used a method
    public static GetAllTestTwoVarIntUseCaseParam build(){
        return new GetAllTestTwoVarIntUseCaseParam();
    }
    
}
