//WANING: this code is autogenerated with GCA by FelipedelosH
package api.crazy.demo.domain.usecases.getAllTestTwoVarIntUseCase;

public class GetAllTestTwoVarIntParam {

    private GetAllTestTwoVarIntParam(){
    }

    //This is static becos not need instance... with put static you utilized without instance.
    //Only used a method
    public static GetAllTestTwoVarIntParam build(){
        return new GetAllTestTwoVarIntParam();
    }
    
}
