//WANING: this code is autogenerated with GCA by FelipedelosH
package api.crazy.demo.infraestructure.entryPoints;

import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RestController;

//Dependencias para "Inyectar caso de uso"
import api.crazy.demo.domain.usecases.getAllTestTwoVarIntUseCase.GetAllTestTwoVarIntUseCase;
import api.crazy.demo.domain.usecases.getAllTestTwoVarIntUseCase.GetAllTestTwoVarIntUseCaseParam;


@RestController
public class getTestTwoVarIntApiRest {

    private final GetAllTestTwoVarIntUseCase getalltesttwovarintusecase;

    public getTestTwoVarIntApiRest(GetAllTestTwoVarIntUseCase getalltesttwovarintusecase){
        this.getalltesttwovarintusecase = getalltesttwovarintusecase;
    }

    @GetMapping("/getAllTestTwoVarInt")
	public String index() {

        var response = getalltesttwovarintusecase.call(GetAllTestTwoVarIntUseCaseParam.build());

		return response.toString();
	}

}
