//WANING: this code is autogenerated with GCA by FelipedelosH
package api.crazy.demo.infraestructure.mappers;

import api.crazy.demo.domain.entities.TestTwoVarInt;
import api.crazy.demo.infraestructure.DAO.TestTwoVarIntDAO.TestTwoVarIntEntity;

public class TestTwoVarIntMapper {


    public static TestTwoVarIntEntity toEntity(TestTwoVarInt testtwovarint) {
        return new TestTwoVarIntEntity(testtwovarint.getId(),testtwovarint.getNumero());
    }
    


    public static TestTwoVarInt toDomain(TestTwoVarIntEntity testtwovarint) {
        return new TestTwoVarInt(testtwovarint.getId(),testtwovarint.getNumero());
    }
    

}
