//WANING: this code is autogenerated with GCA by FelipedelosH
package api.crazy.demo.domain.entities;

public class TestTwoVarInt {
    
	public String id;
	public int numero;


	public TestTwoVarInt(){
	}

	public TestTwoVarInt(String id,int numero){
		this.id = id;
		this.numero = numero;
	}

	public void setId(String id){
		this.id = id;
	}

	public String getId(){
		return this.id;
	}

	public void setNumero(int numero){
		this.numero = numero;
	}

	public int getNumero(){
		return this.numero;
	}




    @Override
    public String toString() {
        return 	"{" +
			"\"id\": \"" + id + "\"," + 
			"\"numero\":"  + numero +
		"}";
    }
    

}
