//WANING: this code is autogenerated with GCA by FelipedelosH
package api.crazy.demo.domain.usecases.getAllExampleUseCase;

public class GetAllExampleUseCaseParam {

    private GetAllExampleUseCaseParam(){
    }

    //This is static becos not need instance... with put static you utilized without instance.
    //Only used a method
    public static GetAllExampleUseCaseParam build(){
        return new GetAllExampleUseCaseParam();
    }
    
}
